# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEKOTpxlgI2DtjhRzKkj_TL9wYR0dNMh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris

Iris=load_iris()
Iris.feature_names

Iris.target_names

dataf=pd.DataFrame(Iris.data,columns=Iris.feature_names)
dataf.head()

dataf.shape

dataf['target']=Iris.target
dataf.head()

dataf[dataf.target==1].head()

dataf[dataf.target==2].head()

dataf["flower_names"]=dataf.target.apply(lambda x:Iris.target_names[x])
dataf.head()

dataf0=dataf[:50]
dataf1=dataf[50:100]
dataf2=dataf[100:]

plt.xlabel("Sepal Length")
plt.ylabel("Sepal Width")
plt.title("Iris Flower")
plt.scatter(dataf0['sepal length (cm)'],dataf0['sepal width (cm)'],color='green',marker='*')
plt.scatter(dataf1['sepal length (cm)'],dataf1['sepal width (cm)'],color='red',marker='+')
plt.scatter(dataf2['sepal length (cm)'],dataf2['sepal width (cm)'],color='yellow',marker='.')

X1=dataf.drop(['target','flower_names'],axis='columns')
Y1=dataf.target

X_train,X_test,Y_train,Y_test=train_test_split(X1,Y1,test_size=0.2)
len(X_train),len(X_test)

knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,Y_train)

knn.score(X_test,Y_test)

y_pred=knn.predict(X_test)

cnn=confusion_matrix(Y_test,y_pred)
cnn

plt.figure(figsize=(10,7))
plt.title("Confusion Matrix of Iris")
sns.heatmap(cnn,annot=True,fmt='d',cmap='Blues')
plt.ylabel("Actual")
plt.xlabel("Predicted")
plt.show()

